# Yang wajib diisi
# 1. nama worker (ubah juga di Cargo.toml)
# 2. account id cloudflare
# 3. KV Storage
# 4. id KV Storage tadi
# 5. UUID

# ===============[ nama worker ]=================
name = "ancient-hat-674f"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

# ===============[ account id ]==================
account_id = "37fef4048777b765f27c5bbe3f431a35"
workers_dev = true

# ===============[ KV STORAGE ]==================
[[kv_namespaces]]
binding = "AIO"
id = "5fb86eaa150b486ba6230c00fdd89e98"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

# =================[ UUID V4 ]===================
[vars]
UUID = "628d410b-e0ac-443b-9c3d-450d403cac08"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/flexcare19/biznet/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/flexcare19/biznet/refs/heads/main/web/sub.html"

# ------- Dimodifikasi oleh: @technic -------
